const PERFORMANCE_DATA = {
  "summary": {
    "tracked": 29,
    "launched": 0,
    "planned": 29,
    "impressions": 0,
    "downloads": 0,
    "leads": 0,
    "paid": 0,
    "revenue": 0.0
  },
  "rows": [
    {
      "date": "2026-07-08",
      "platform": "小红书图文 + 抖音短视频",
      "skill": "AI 内容人味化总监",
      "slug": "ai-content-humanizer-director",
      "post_url": "",
      "format": "痛点清单",
      "owner": "小燃",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "内容增长",
      "score": 100,
      "channel": "小红书图文 + 抖音短视频",
      "hook": "别再发一眼 AI 的文案了：给我原文，我帮你改成能发的小红书/抖音版本。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-09",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "skill": "GTM 获客工程师 Skill 包",
      "slug": "gtm-engineer-skill-pack",
      "post_url": "",
      "format": "前后对比",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "销售成交",
      "score": 100,
      "channel": "LinkedIn/公众号案例 + 小红书工具分享",
      "hook": "别一上来投广告，先用 30 天 GTM 实验验证谁真的会买。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-10",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "skill": "LinkedIn 增长 Skill 包",
      "slug": "linkedin-growth-skill-pack",
      "post_url": "",
      "format": "现场演示",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "销售成交",
      "score": 100,
      "channel": "LinkedIn/公众号案例 + 小红书工具分享",
      "hook": "B2B 获客不是群发私信，而是主页、内容、评论和暖私信一起跑。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-11",
      "platform": "抖音/视频号演示 + 小红书教程",
      "skill": "视频切片与剪辑流程总监",
      "slug": "video-cut-workflow-director",
      "post_url": "",
      "format": "模板领取",
      "owner": "小燃",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "短视频转化",
      "score": 98,
      "channel": "抖音/视频号演示 + 小红书教程",
      "hook": "一条长视频不知道剪哪里？先让 Skill 帮你找爆点和切片顺序。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 44
    },
    {
      "date": "2026-07-12",
      "platform": "GitHub/公众号/小红书技术运营",
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "post_url": "",
      "format": "案例拆解",
      "owner": "阿序",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "产品增长",
      "score": 94,
      "channel": "GitHub/公众号/小红书技术运营",
      "hook": "每天自动找高星 Skill，不靠灵感，靠市场已经投票过的需求。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-13",
      "platform": "小红书职场 + 公众号长文",
      "skill": "图片/PDF 转可编辑 PPT 助手",
      "slug": "image-to-editable-ppt-assistant",
      "post_url": "",
      "format": "避坑提醒",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 96,
      "channel": "小红书职场 + 公众号长文",
      "hook": "截图和 PDF 也能变成可编辑 PPT，适合周报、方案和老板汇报。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 43
    },
    {
      "date": "2026-07-14",
      "platform": "小红书设计/运营图文",
      "skill": "内容视觉卡片系统",
      "slug": "visual-card-content-system",
      "post_url": "",
      "format": "合集打包",
      "owner": "南枝",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "视觉转化",
      "score": 93,
      "channel": "小红书设计/运营图文",
      "hook": "把一句观点做成能收藏的卡片，比单纯发文字更容易传播。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-15",
      "platform": "LinkedIn + 小红书跨境圈",
      "skill": "LinkedIn 社交销售系统",
      "slug": "linkedin-social-selling-system",
      "post_url": "",
      "format": "痛点清单",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "海外增长",
      "score": 93,
      "channel": "LinkedIn + 小红书跨境圈",
      "hook": "B2B 获客不是群发私信，而是主页、内容、评论和暖私信一起跑。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-16",
      "platform": "小红书卖家圈 + 公众号案例",
      "skill": "Amazon/Shopify Listing 转化包",
      "slug": "amazon-shopify-listing-conversion-pack",
      "post_url": "",
      "format": "前后对比",
      "owner": "Mia",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "电商转化",
      "score": 92,
      "channel": "小红书卖家圈 + 公众号案例",
      "hook": "Listing 不是翻译参数，而是把卖点、信任和购买顾虑一次讲清楚。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-17",
      "platform": "小红书卖家圈 + 公众号案例",
      "skill": "跨境电商运营负责人",
      "slug": "crossborder-commerce-operator",
      "post_url": "",
      "format": "现场演示",
      "owner": "Mia",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "电商转化",
      "score": 92,
      "channel": "小红书卖家圈 + 公众号案例",
      "hook": "跨境卖家最缺的不是想法，是从选品到转化素材的一条闭环。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-18",
      "platform": "小红书职场 + 公众号长文",
      "skill": "PPT 汇报大纲工作室",
      "slug": "ppt-report-outline-studio",
      "post_url": "",
      "format": "模板领取",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 91,
      "channel": "小红书职场 + 公众号长文",
      "hook": "截图和 PDF 也能变成可编辑 PPT，适合周报、方案和老板汇报。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-19",
      "platform": "小红书职场 + 公众号长文",
      "skill": "办公效率参谋长",
      "slug": "office-productivity-chief",
      "post_url": "",
      "format": "案例拆解",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 91,
      "channel": "小红书职场 + 公众号长文",
      "hook": "办公效率参谋长：把高频业务动作封装成一个可下载 Skill。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-20",
      "platform": "小红书运营圈 + 私域社群",
      "skill": "微信私域问题聚类",
      "slug": "wechat-private-domain-question-cluster",
      "post_url": "",
      "format": "避坑提醒",
      "owner": "苏苏",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "私域成交",
      "score": 90,
      "channel": "小红书运营圈 + 私域社群",
      "hook": "评论和私信里藏着成交机会，关键是别只会机械回复。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 40
    },
    {
      "date": "2026-07-21",
      "platform": "小红书运营圈 + 私域社群",
      "skill": "社群私信成交话术包",
      "slug": "community-private-message-close-pack",
      "post_url": "",
      "format": "合集打包",
      "owner": "苏苏",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "私域成交",
      "score": 90,
      "channel": "小红书运营圈 + 私域社群",
      "hook": "评论和私信里藏着成交机会，关键是别只会机械回复。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 40
    },
    {
      "date": "2026-07-09",
      "platform": "小红书图文 + 抖音短视频",
      "skill": "AI 内容人味化总监",
      "slug": "ai-content-humanizer-director",
      "post_url": "",
      "format": "痛点清单",
      "owner": "小燃",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "内容增长",
      "score": 100,
      "channel": "小红书图文 + 抖音短视频",
      "hook": "别再发一眼 AI 的文案了：给我原文，我帮你改成能发的小红书/抖音版本。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-10",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "skill": "GTM 获客工程师 Skill 包",
      "slug": "gtm-engineer-skill-pack",
      "post_url": "",
      "format": "前后对比",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "销售成交",
      "score": 100,
      "channel": "LinkedIn/公众号案例 + 小红书工具分享",
      "hook": "别一上来投广告，先用 30 天 GTM 实验验证谁真的会买。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-11",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "skill": "LinkedIn 增长 Skill 包",
      "slug": "linkedin-growth-skill-pack",
      "post_url": "",
      "format": "现场演示",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "销售成交",
      "score": 100,
      "channel": "LinkedIn/公众号案例 + 小红书工具分享",
      "hook": "B2B 获客不是群发私信，而是主页、内容、评论和暖私信一起跑。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 45
    },
    {
      "date": "2026-07-12",
      "platform": "抖音/视频号演示 + 小红书教程",
      "skill": "视频切片与剪辑流程总监",
      "slug": "video-cut-workflow-director",
      "post_url": "",
      "format": "模板领取",
      "owner": "小燃",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "短视频转化",
      "score": 98,
      "channel": "抖音/视频号演示 + 小红书教程",
      "hook": "一条长视频不知道剪哪里？先让 Skill 帮你找爆点和切片顺序。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 44
    },
    {
      "date": "2026-07-13",
      "platform": "GitHub/公众号/小红书技术运营",
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "post_url": "",
      "format": "案例拆解",
      "owner": "阿序",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "产品增长",
      "score": 94,
      "channel": "GitHub/公众号/小红书技术运营",
      "hook": "每天自动找高星 Skill，不靠灵感，靠市场已经投票过的需求。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-14",
      "platform": "小红书职场 + 公众号长文",
      "skill": "图片/PDF 转可编辑 PPT 助手",
      "slug": "image-to-editable-ppt-assistant",
      "post_url": "",
      "format": "避坑提醒",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 96,
      "channel": "小红书职场 + 公众号长文",
      "hook": "截图和 PDF 也能变成可编辑 PPT，适合周报、方案和老板汇报。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 43
    },
    {
      "date": "2026-07-15",
      "platform": "小红书设计/运营图文",
      "skill": "内容视觉卡片系统",
      "slug": "visual-card-content-system",
      "post_url": "",
      "format": "合集打包",
      "owner": "南枝",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "视觉转化",
      "score": 93,
      "channel": "小红书设计/运营图文",
      "hook": "把一句观点做成能收藏的卡片，比单纯发文字更容易传播。",
      "cta": "评论「模板」领取免费 Skill；合集和一对一调试走私信。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-16",
      "platform": "LinkedIn + 小红书跨境圈",
      "skill": "LinkedIn 社交销售系统",
      "slug": "linkedin-social-selling-system",
      "post_url": "",
      "format": "痛点清单",
      "owner": "Leo",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "海外增长",
      "score": 93,
      "channel": "LinkedIn + 小红书跨境圈",
      "hook": "B2B 获客不是群发私信，而是主页、内容、评论和暖私信一起跑。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    },
    {
      "date": "2026-07-17",
      "platform": "小红书卖家圈 + 公众号案例",
      "skill": "Amazon/Shopify Listing 转化包",
      "slug": "amazon-shopify-listing-conversion-pack",
      "post_url": "",
      "format": "前后对比",
      "owner": "Mia",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "电商转化",
      "score": 92,
      "channel": "小红书卖家圈 + 公众号案例",
      "hook": "Listing 不是翻译参数，而是把卖点、信任和购买顾虑一次讲清楚。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-18",
      "platform": "小红书卖家圈 + 公众号案例",
      "skill": "跨境电商运营负责人",
      "slug": "crossborder-commerce-operator",
      "post_url": "",
      "format": "现场演示",
      "owner": "Mia",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "电商转化",
      "score": 92,
      "channel": "小红书卖家圈 + 公众号案例",
      "hook": "跨境卖家最缺的不是想法，是从选品到转化素材的一条闭环。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-19",
      "platform": "小红书职场 + 公众号长文",
      "skill": "PPT 汇报大纲工作室",
      "slug": "ppt-report-outline-studio",
      "post_url": "",
      "format": "模板领取",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 91,
      "channel": "小红书职场 + 公众号长文",
      "hook": "截图和 PDF 也能变成可编辑 PPT，适合周报、方案和老板汇报。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-20",
      "platform": "小红书职场 + 公众号长文",
      "skill": "办公效率参谋长",
      "slug": "office-productivity-chief",
      "post_url": "",
      "format": "案例拆解",
      "owner": "简白",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "办公提效",
      "score": 91,
      "channel": "小红书职场 + 公众号长文",
      "hook": "办公效率参谋长：把高频业务动作封装成一个可下载 Skill。",
      "cta": "评论「办公」领取安装包；需要部署教程和答疑可进群。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 41
    },
    {
      "date": "2026-07-21",
      "platform": "小红书运营圈 + 私域社群",
      "skill": "微信私域问题聚类",
      "slug": "wechat-private-domain-question-cluster",
      "post_url": "",
      "format": "避坑提醒",
      "owner": "苏苏",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "私域成交",
      "score": 90,
      "channel": "小红书运营圈 + 私域社群",
      "hook": "评论和私信里藏着成交机会，关键是别只会机械回复。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 40
    },
    {
      "date": "2026-07-22",
      "platform": "小红书运营圈 + 私域社群",
      "skill": "社群私信成交话术包",
      "slug": "community-private-message-close-pack",
      "post_url": "",
      "format": "合集打包",
      "owner": "苏苏",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "私域成交",
      "score": 90,
      "channel": "小红书运营圈 + 私域社群",
      "hook": "评论和私信里藏着成交机会，关键是别只会机械回复。",
      "cta": "评论关键词领取免费包；复杂场景私信做诊断。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 40
    },
    {
      "date": "2026-07-14",
      "platform": "GitHub/公众号/小红书技术运营",
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "post_url": "",
      "format": "避坑提醒",
      "owner": "阿序",
      "status": "planned",
      "impressions": "",
      "likes": "",
      "saves": "",
      "comments": "",
      "dms": "",
      "downloads": "",
      "leads": "",
      "paid_conversions": "",
      "revenue": "",
      "notes": "",
      "business": "产品增长",
      "score": 94,
      "channel": "GitHub/公众号/小红书技术运营",
      "hook": "每天自动找高星 Skill，不靠灵感，靠市场已经投票过的需求。",
      "cta": "评论/私信「Skill」领取免费版；需要接入业务流程可预约定制。",
      "impressions_int": 0,
      "likes_int": 0,
      "saves_int": 0,
      "comments_int": 0,
      "dms_int": 0,
      "downloads_int": 0,
      "leads_int": 0,
      "paid_int": 0,
      "revenue_float": 0.0,
      "engagement_int": 0,
      "engagement_rate": 0.0,
      "save_rate": 0.0,
      "comment_rate": 0.0,
      "dm_rate": 0.0,
      "download_rate": 0.0,
      "lead_rate": 0.0,
      "conversion_rate": 0.0,
      "recommendation": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "priority_score": 42
    }
  ],
  "experiments": [
    {
      "skill": "AI 内容人味化总监",
      "slug": "ai-content-humanizer-director",
      "platform": "小红书图文 + 抖音短视频",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "AI 内容人味化总监",
      "slug": "ai-content-humanizer-director",
      "platform": "小红书图文 + 抖音短视频",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "GTM 获客工程师 Skill 包",
      "slug": "gtm-engineer-skill-pack",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "GTM 获客工程师 Skill 包",
      "slug": "gtm-engineer-skill-pack",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "LinkedIn 增长 Skill 包",
      "slug": "linkedin-growth-skill-pack",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "LinkedIn 增长 Skill 包",
      "slug": "linkedin-growth-skill-pack",
      "platform": "LinkedIn/公众号案例 + 小红书工具分享",
      "priority": 45,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "视频切片与剪辑流程总监",
      "slug": "video-cut-workflow-director",
      "platform": "抖音/视频号演示 + 小红书教程",
      "priority": 44,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "视频切片与剪辑流程总监",
      "slug": "video-cut-workflow-director",
      "platform": "抖音/视频号演示 + 小红书教程",
      "priority": 44,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "图片/PDF 转可编辑 PPT 助手",
      "slug": "image-to-editable-ppt-assistant",
      "platform": "小红书职场 + 公众号长文",
      "priority": 43,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "图片/PDF 转可编辑 PPT 助手",
      "slug": "image-to-editable-ppt-assistant",
      "platform": "小红书职场 + 公众号长文",
      "priority": 43,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "platform": "GitHub/公众号/小红书技术运营",
      "priority": 42,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "platform": "GitHub/公众号/小红书技术运营",
      "priority": 42,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "内容视觉卡片系统",
      "slug": "visual-card-content-system",
      "platform": "小红书设计/运营图文",
      "priority": 42,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    },
    {
      "skill": "强 Skill 市场雷达策展官",
      "slug": "skill-market-curator",
      "platform": "GitHub/公众号/小红书技术运营",
      "priority": 42,
      "signal": "先发布并记录首轮数据，至少填曝光、收藏、评论、私信和下载。",
      "action": "先把这条内容发出去，并在 24 小时内补齐曝光、收藏、评论、私信、下载数据。",
      "success_metric": "至少补齐 5 个核心字段，并拿到第一轮真实反馈。"
    }
  ]
};

function el(id) {
  return document.getElementById(id);
}

function renderSummary() {
  const cards = [
    {
      eyebrow: "Tracked",
      value: PERFORMANCE_DATA.summary.tracked,
      title: "纳入复盘",
      note: "当前正在跟踪的内容条目数量。"
    },
    {
      eyebrow: "Launched",
      value: PERFORMANCE_DATA.summary.launched,
      title: "已有首轮数据",
      note: "已经填写过曝光、互动或下载数据的条目。"
    },
    {
      eyebrow: "Downloads",
      value: PERFORMANCE_DATA.summary.downloads,
      title: "累计下载",
      note: "免费包有没有被真正领取，是进入线索的第一道关。"
    },
    {
      eyebrow: "Leads",
      value: PERFORMANCE_DATA.summary.leads,
      title: "累计线索",
      note: "有人留下具体场景、预算或付费意向。"
    },
    {
      eyebrow: "Paid",
      value: PERFORMANCE_DATA.summary.paid,
      title: "累计付费",
      note: "已经愿意买教程、社群或定制服务。"
    },
    {
      eyebrow: "Revenue",
      value: PERFORMANCE_DATA.summary.revenue,
      title: "累计营收",
      note: "方便判断该不该继续给这个方向投时间。"
    }
  ];
  el("summaryCards").innerHTML = cards.map((card, index) => `
    <article class="review-card ${index === 0 ? "lead" : ""}">
      <p class="eyebrow">${card.eyebrow}</p>
      <div class="review-score">${card.value}</div>
      <h3>${card.title}</h3>
      <p class="small-muted">${card.note}</p>
    </article>
  `).join("");
}

function renderTable() {
  const rows = PERFORMANCE_DATA.rows.slice().sort((a, b) => b.priority_score - a.priority_score).slice(0, 18);
  el("reviewTable").innerHTML = `
    <thead><tr><th>#</th><th>Skill</th><th>平台</th><th>曝光</th><th>下载</th><th>线索</th><th>付费</th><th>收藏率</th><th>私信率</th><th>建议动作</th></tr></thead>
    <tbody>
      ${rows.map((row, index) => `
        <tr>
          <td>${index + 1}</td>
          <td>${row.skill}</td>
          <td>${row.platform}</td>
          <td>${row.impressions_int}</td>
          <td>${row.downloads_int}</td>
          <td>${row.leads_int}</td>
          <td>${row.paid_int}</td>
          <td>${row.save_rate}%</td>
          <td>${row.dm_rate}%</td>
          <td>${row.recommendation}</td>
        </tr>
      `).join("")}
    </tbody>
  `;
}

function renderExperiments() {
  el("experimentList").innerHTML = PERFORMANCE_DATA.experiments.slice(0, 8).map((item) => `
    <article class="experiment-card">
      <p class="eyebrow">优先级 ${item.priority}</p>
      <h3>${item.skill}</h3>
      <p><strong>当前信号：</strong>${item.signal}</p>
      <p><strong>本轮实验：</strong>${item.action}</p>
      <p class="small-muted">成功标准：${item.success_metric}</p>
    </article>
  `).join("");
}

function renderDetailList(activeSlug = PERFORMANCE_DATA.rows[0]?.slug) {
  el("detailList").innerHTML = PERFORMANCE_DATA.rows.map((row) => `
    <button class="detail-button ${row.slug === activeSlug ? "active" : ""}" type="button" data-slug="${row.slug}">
      <strong>${row.skill}</strong><br />
      <span class="small-muted">${row.date} · ${row.platform}</span>
    </button>
  `).join("");
  el("detailList").querySelectorAll("button").forEach((button) => {
    button.addEventListener("click", () => renderDetail(button.dataset.slug));
  });
}

function renderDetail(slug = PERFORMANCE_DATA.rows[0]?.slug) {
  const row = PERFORMANCE_DATA.rows.find((item) => item.slug === slug) || PERFORMANCE_DATA.rows[0];
  if (!row) {
    return;
  }
  renderDetailList(row.slug);
  el("detailCard").innerHTML = `
    <p class="eyebrow">${row.date} · ${row.platform}</p>
    <h3>${row.skill}</h3>
    <p><strong>业务：</strong>${row.business || "待确认"}</p>
    <p><strong>负责人：</strong>${row.owner || "阿序"}</p>
    <div class="detail-box">状态：${row.status || "planned"}\n曝光：${row.impressions_int}\n点赞：${row.likes_int}\n收藏：${row.saves_int}\n评论：${row.comments_int}\n私信：${row.dms_int}\n下载：${row.downloads_int}\n线索：${row.leads_int}\n付费：${row.paid_int}\n收藏率：${row.save_rate}%\n评论率：${row.comment_rate}%\n私信率：${row.dm_rate}%\n线索率：${row.lead_rate}%\n成交率：${row.conversion_rate}%\n\n建议动作：${row.recommendation}\n\n钩子：${row.hook || "待补充"}\nCTA：${row.cta || "待补充"}\n备注：${row.notes || "暂无"}\n链接：${row.post_url || "待填写"} </div>
  `;
}

function init() {
  el("reviewTracked").textContent = PERFORMANCE_DATA.summary.tracked;
  el("reviewLaunched").textContent = PERFORMANCE_DATA.summary.launched;
  el("reviewLeads").textContent = PERFORMANCE_DATA.summary.leads;
  renderSummary();
  renderTable();
  renderExperiments();
  renderDetail();
}

init();
